/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: THunter (https://sketchfab.com/TwilightHunter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magma-staff-891292e7c89143db884c83cb976a0e54
Title: Magma Staff
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/magicienWand.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.116, 0.116, 0]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.MagSt1__0.geometry}
            material={materials['Scene_-_Root']}
            position={[0, 74.747, 0]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[0.284, 0.335, 0.284]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/magicienWand.glb')